/**
 * Config plugin: inject a real `signingConfigs.release` into the Android
 * project generated by `expo prebuild`.
 *
 * Why a plugin instead of editing `android/app/build.gradle` by hand?
 * `mobile/android/` is generated by `expo prebuild` and is gitignored
 * (see `mobile/.gitignore` → `/android`). Any manual edit is wiped on the
 * next prebuild, and CI always runs `expo prebuild --clean`. So the signing
 * configuration has to be re-applied programmatically on every prebuild —
 * exactly the job of an Expo config plugin (same reasoning as
 * `withAsyncStorageDbSize.js`).
 *
 * What the Expo template ships with (RN 0.85 / Expo 56):
 *
 *   signingConfigs {
 *       debug { storeFile file('debug.keystore') ... }
 *   }
 *   buildTypes {
 *       release {
 *           // Caution! In production, you need to generate your own keystore file.
 *           signingConfig signingConfigs.debug
 *           ...
 *       }
 *   }
 *
 * i.e. release builds are signed with the throwaway debug keystore, which
 * Google Play rejects. This plugin:
 *
 *   1. adds a `release` entry to `signingConfigs` that resolves the keystore
 *      coordinates from, in order of precedence:
 *        a. `android/app/signing.properties`  (storeFile / storePassword /
 *           keyAlias / keyPassword — same file/keys the old Ionic pipeline
 *           used, kept for continuity)
 *        b. Gradle properties `MYAPP_UPLOAD_STORE_FILE`,
 *           `MYAPP_UPLOAD_STORE_PASSWORD`, `MYAPP_UPLOAD_KEY_ALIAS`,
 *           `MYAPP_UPLOAD_KEY_PASSWORD` (written into `android/gradle.properties`
 *           by this same plugin, see step 3)
 *        c. environment variables with those same names
 *   2. points `buildTypes.release` at `signingConfigs.release` **only when a
 *      keystore was actually resolved**, otherwise it keeps falling back to
 *      the debug keystore — so `npx expo run:android --variant release` still
 *      works on a dev machine with no keystore at hand.
 *   3. mirrors any `MYAPP_UPLOAD_*` environment variable present at prebuild
 *      time into `android/gradle.properties`, which is how CI hands the
 *      keystore coordinates to Gradle (`android/` is gitignored and the CI
 *      runner is ephemeral, so nothing is persisted).
 *
 * The keystore file itself is never committed: CI decodes the
 * `ANDROID_KEYSTORE_BASE64` secret to `android/app/release.keystore`.
 */

const {
  withAppBuildGradle,
  withGradleProperties,
} = require('expo/config-plugins');

/** Gradle/env property names carrying the keystore coordinates. */
const SIGNING_PROPERTY_KEYS = [
  'MYAPP_UPLOAD_STORE_FILE',
  'MYAPP_UPLOAD_STORE_PASSWORD',
  'MYAPP_UPLOAD_KEY_ALIAS',
  'MYAPP_UPLOAD_KEY_PASSWORD',
];

/** Marker used to detect an already-patched build.gradle (idempotency). */
const RELEASE_SIGNING_MARKER = 'MYAPP_UPLOAD_STORE_FILE';

/** The `release { ... }` entry added inside `signingConfigs { ... }`. */
const RELEASE_SIGNING_CONFIG = `
        // Injected by plugins/withReleaseSigning.js — do not edit by hand,
        // android/ is regenerated by \`expo prebuild --clean\`.
        release {
            def uvaSigningProps = new Properties()
            def uvaSigningPropsFile = file('signing.properties')
            if (uvaSigningPropsFile.exists()) {
                uvaSigningPropsFile.withInputStream { uvaSigningProps.load(it) }
            }
            def uvaResolve = { String propertyName, String fileKey ->
                if (uvaSigningProps.getProperty(fileKey)) {
                    return uvaSigningProps.getProperty(fileKey)
                }
                if (project.hasProperty(propertyName) && project.property(propertyName)) {
                    return project.property(propertyName)
                }
                return System.getenv(propertyName)
            }
            def uvaStoreFile = uvaResolve('MYAPP_UPLOAD_STORE_FILE', 'storeFile')
            if (uvaStoreFile) {
                storeFile file(uvaStoreFile)
                storePassword uvaResolve('MYAPP_UPLOAD_STORE_PASSWORD', 'storePassword')
                keyAlias uvaResolve('MYAPP_UPLOAD_KEY_ALIAS', 'keyAlias')
                keyPassword uvaResolve('MYAPP_UPLOAD_KEY_PASSWORD', 'keyPassword')
            }
        }`;

/** Replaces the template's `signingConfig signingConfigs.debug` in buildTypes.release. */
const RELEASE_SIGNING_SELECTOR =
  'signingConfig signingConfigs.release.storeFile != null ? signingConfigs.release : signingConfigs.debug';

/**
 * Patch the contents of `android/app/build.gradle`.
 * Exported for unit testing.
 *
 * @param {string} contents raw build.gradle (Groovy) source
 * @returns {string} patched source
 */
function addReleaseSigningConfig(contents) {
  if (contents.includes(RELEASE_SIGNING_MARKER)) {
    // Already patched (e.g. prebuild ran twice without --clean).
    return contents;
  }

  const signingConfigsMatch = contents.match(/signingConfigs\s*\{/);
  if (!signingConfigsMatch || signingConfigsMatch.index === undefined) {
    throw new Error(
      '[withReleaseSigning] Could not find a `signingConfigs {` block in android/app/build.gradle. ' +
        'The Expo Android template changed — update plugins/withReleaseSigning.js.',
    );
  }

  // Order inside `signingConfigs { }` is irrelevant to Gradle, so we insert
  // the `release` entry right after the opening brace.
  const insertAt = signingConfigsMatch.index + signingConfigsMatch[0].length;
  let patched =
    contents.slice(0, insertAt) +
    RELEASE_SIGNING_CONFIG +
    contents.slice(insertAt);

  // Point buildTypes.release at the release signing config (with a debug
  // fallback when no keystore is configured).
  const buildTypesIndex = patched.indexOf('buildTypes {');
  if (buildTypesIndex === -1) {
    throw new Error(
      '[withReleaseSigning] Could not find a `buildTypes {` block in android/app/build.gradle.',
    );
  }
  const releaseIndex = patched.indexOf('release {', buildTypesIndex);
  if (releaseIndex === -1) {
    throw new Error(
      '[withReleaseSigning] Could not find `release {` inside `buildTypes` in android/app/build.gradle.',
    );
  }
  const debugSigning = 'signingConfig signingConfigs.debug';
  const debugSigningIndex = patched.indexOf(debugSigning, releaseIndex);
  if (debugSigningIndex === -1) {
    throw new Error(
      '[withReleaseSigning] Could not find `signingConfig signingConfigs.debug` inside ' +
        '`buildTypes.release` in android/app/build.gradle.',
    );
  }
  patched =
    patched.slice(0, debugSigningIndex) +
    RELEASE_SIGNING_SELECTOR +
    patched.slice(debugSigningIndex + debugSigning.length);

  return patched;
}

/**
 * Mirror the `MYAPP_UPLOAD_*` env vars present at prebuild time into the
 * parsed `gradle.properties` item list.
 * Exported for unit testing.
 *
 * @param {{type: string, key?: string, value?: string}[]} properties
 * @param {Record<string, string | undefined>} env
 * @returns {{type: string, key?: string, value?: string}[]}
 */
function applySigningGradleProperties(properties, env) {
  for (const key of SIGNING_PROPERTY_KEYS) {
    const value = env[key];
    if (!value) {
      continue;
    }
    const existing = properties.find(
      (item) => item.type === 'property' && item.key === key,
    );
    if (existing) {
      existing.value = value;
    } else {
      properties.push({ type: 'property', key, value });
    }
  }
  return properties;
}

/**
 * @param {import('expo/config-plugins').ExportedConfig} config
 */
const withReleaseSigning = (config) => {
  config = withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error(
        '[withReleaseSigning] Only the Groovy build.gradle is supported (got ' +
          gradleConfig.modResults.language +
          ').',
      );
    }
    gradleConfig.modResults.contents = addReleaseSigningConfig(
      gradleConfig.modResults.contents,
    );
    return gradleConfig;
  });

  config = withGradleProperties(config, (gradleConfig) => {
    gradleConfig.modResults = applySigningGradleProperties(
      gradleConfig.modResults,
      process.env,
    );
    return gradleConfig;
  });

  return config;
};

module.exports = withReleaseSigning;
module.exports.addReleaseSigningConfig = addReleaseSigningConfig;
module.exports.applySigningGradleProperties = applySigningGradleProperties;
module.exports.SIGNING_PROPERTY_KEYS = SIGNING_PROPERTY_KEYS;
