projects:
  Codegen Project:
    schemaPath: schema.json
    includes:
      - src/data/graphql/**/*.ts
    excludes:
      - ./amplify/**
      - src/data/graphql/API.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/data/graphql/API.ts
        docsFilePath: src/data/graphql
        region: us-east-1
        apiId: uqr6xntysfa3lbguhirvcj3pa4
        frontend: javascript
        framework: react-native
        maxDepth: 2
extensions:
  amplify:
    version: 3
