/**
 * Dynamic Expo config.
 *
 * `app.json` stays the single source of truth for everything static: Expo
 * reads it first and hands its `expo` object to this function as `config`.
 * This file only overlays the two values CI needs to inject at build time,
 * because a static JSON file cannot read environment variables:
 *
 *   EXPO_APP_VERSION          → expo.version           (versionName)
 *   EXPO_ANDROID_VERSION_CODE → expo.android.versionCode
 *
 * Both fall back to the values committed in `app.json` when unset, so local
 * `expo prebuild` / `expo run:android` keep behaving exactly as before.
 *
 * Why env instead of patching the generated build.gradle (what the old Ionic
 * pipeline did with three layers of sed/awk fallbacks): `android/` is
 * regenerated by `expo prebuild --clean` on every CI run, so the version has
 * to come from the Expo config, which is the input to that generation.
 *
 * versionCode contract: Google Play only accepts a *strictly increasing*
 * integer. The published reference build is 178830096, and the pipeline
 * derives new codes from `date +%s / 10` (a new code every 10 s), which is
 * already ~1789xxxxx and keeps growing — same strategy the Ionic pipeline
 * used. The workflow asserts `> 178830096` before building.
 */

const MIN_ANDROID_VERSION_CODE = 178830096;

/**
 * @param {{ config: import('expo/config').ExpoConfig }} params
 * @returns {import('expo/config').ExpoConfig}
 */
module.exports = ({ config }) => {
  const rawVersionCode = process.env.EXPO_ANDROID_VERSION_CODE;
  const version = process.env.EXPO_APP_VERSION || config.version;

  let versionCode = config.android?.versionCode;
  if (rawVersionCode) {
    const parsed = Number.parseInt(rawVersionCode, 10);
    if (!Number.isInteger(parsed) || parsed <= MIN_ANDROID_VERSION_CODE) {
      throw new Error(
        `[app.config.js] EXPO_ANDROID_VERSION_CODE must be an integer greater than ` +
          `${MIN_ANDROID_VERSION_CODE} (the versionCode already published on Google Play). ` +
          `Got: "${rawVersionCode}".`,
      );
    }
    versionCode = parsed;
  }

  return {
    ...config,
    version,
    android: {
      ...config.android,
      versionCode,
    },
  };
};

module.exports.MIN_ANDROID_VERSION_CODE = MIN_ANDROID_VERSION_CODE;
