/**
 * Config plugin: raise the SQLite size cap used by
 * `@react-native-async-storage/async-storage` on Android.
 *
 * By default that library's `android/config.gradle` caps its internal
 * SQLite database (`RKStorage`) at 6 MB (`getDatabaseSize()` in
 * `node_modules/@react-native-async-storage/async-storage/android/config.gradle`).
 * On real devices, once Amplify DataStore (which uses AsyncStorage as its
 * default storage adapter) syncs enough measurement history, the DB fills up
 * exactly at that ceiling and every write throws an uncaught
 * `SQLiteFullException: database or disk is full (code 13 SQLITE_FULL)`.
 *
 * The library reads the cap from a Gradle property named
 * `AsyncStorage_db_size_in_MB` (see the same config.gradle, and the
 * package's README under "Database size"). Since `mobile/android/` is
 * generated by `expo prebuild` and is gitignored, we can't hand-edit
 * `android/gradle.properties` directly — it would be wiped on every
 * prebuild. Instead we inject the property via a config plugin using
 * `withGradleProperties` from `expo/config-plugins`.
 *
 * Why not `expo-build-properties`? The version installed in this project
 * (56.0.18) only exposes a fixed, typed set of Android knobs
 * (minSdkVersion, compileSdkVersion, targetSdkVersion, buildToolsVersion,
 * packagingOptions, etc.) — there is no generic "arbitrary gradle property"
 * escape hatch (see `node_modules/expo-build-properties/build/pluginConfig.d.ts`).
 * So a small dedicated plugin is the simplest correct option.
 */

const { withGradleProperties } = require('expo/config-plugins');

const PROPERTY_KEY = 'AsyncStorage_db_size_in_MB';
const PROPERTY_VALUE = '200';

/**
 * @param {import('expo/config-plugins').ExportedConfig} config
 */
const withAsyncStorageDbSize = (config) => {
  return withGradleProperties(config, (config) => {
    const properties = config.modResults;
    const existing = properties.find(
      (item) => item.type === 'property' && item.key === PROPERTY_KEY,
    );

    if (existing) {
      existing.value = PROPERTY_VALUE;
    } else {
      properties.push({
        type: 'property',
        key: PROPERTY_KEY,
        value: PROPERTY_VALUE,
      });
    }

    return config;
  });
};

module.exports = withAsyncStorageDbSize;
