/**
 * Config plugin: restrict the native ABIs React Native builds/packages.
 *
 * The Expo Android template ships with
 *
 *   reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
 *
 * in `android/gradle.properties`. `x86` and `x86_64` only exist to run the
 * app on an Android *emulator*; no phone or tablet on Google Play uses them.
 * Keeping them costs ~22 MB of `.so` files **per ABI** in the universal APK
 * (`assembleRelease`) and ~24 MB of compressed payload in the AAB, plus the
 * CMake/NDK build time of every library that compiles C++ from source
 * (reanimated, worklets, rnscreens, rnsvg, expo-modules-core…).
 *
 * Google Play serves per-ABI splits from the AAB, so dropping x86/x86_64 does
 * **not** change what a real device downloads — but it does shrink the AAB
 * that gets uploaded and, above all, the universal APK that QA installs by
 * hand (which is the number people actually look at).
 *
 * Why a gradle property instead of `buildTypes.release { ndk { abiFilters … } }`:
 * AGP merges `ndk.abiFilters` as a **union** across `defaultConfig` and the
 * build type, so a build-type-scoped filter cannot *remove* an ABI that the
 * default config already includes — it would be a no-op. The React Native
 * Gradle plugin reads `reactNativeArchitectures` at configuration time, which
 * is the only supported knob, and it is global to the project.
 *
 * Why a plugin instead of editing `android/gradle.properties` by hand:
 * `mobile/android/` is generated by `expo prebuild` and is gitignored
 * (see `mobile/.gitignore` → `/android`), so a manual edit is wiped on every
 * prebuild and CI always runs `expo prebuild --clean`. Same reasoning as
 * `withAsyncStorageDbSize.js` and `withReleaseSigning.js`.
 *
 * Why not `expo-build-properties`: the version installed here (56.0.18) only
 * exposes a fixed, typed set of Android knobs (minSdkVersion, targetSdkVersion,
 * enableMinifyInReleaseBuilds, extraProguardRules, packagingOptions…) — there
 * is no generic "arbitrary gradle property" escape hatch
 * (`node_modules/expo-build-properties/build/pluginConfig.d.ts`).
 *
 * ── Running on an x86_64 emulator ─────────────────────────────────────────
 * Two documented escape hatches, in order of convenience:
 *
 *   1. Per-invocation, no prebuild needed — the override the Expo template
 *      itself documents in `gradle.properties`:
 *        cd android && ./gradlew assembleDebug -PreactNativeArchitectures=x86_64
 *
 *   2. Per-prebuild, via the env var read below:
 *        EXPO_ANDROID_ARCHITECTURES=armeabi-v7a,arm64-v8a,x86,x86_64 \
 *          npx expo prebuild --platform android --clean
 *
 * Debug builds for a *physical* device (arm64) are unaffected.
 */

const { withGradleProperties } = require('expo/config-plugins');

const PROPERTY_KEY = 'reactNativeArchitectures';

/** ABIs shipped to Google Play. x86/x86_64 are emulator-only. */
const DEFAULT_ARCHITECTURES = 'armeabi-v7a,arm64-v8a';

/** Env var to override the list (see docblock). */
const ENV_VAR = 'EXPO_ANDROID_ARCHITECTURES';

/**
 * Resolve the ABI list, preferring the env var when it is set and non-empty.
 * Exported for unit testing.
 *
 * @param {Record<string, string | undefined>} env
 * @returns {string} comma-separated ABI list
 */
function resolveArchitectures(env) {
  const raw = env[ENV_VAR];
  if (typeof raw !== 'string') {
    return DEFAULT_ARCHITECTURES;
  }
  const cleaned = raw
    .split(',')
    .map((abi) => abi.trim())
    .filter(Boolean)
    .join(',');
  return cleaned || DEFAULT_ARCHITECTURES;
}

/**
 * Set (or replace) `reactNativeArchitectures` in the parsed gradle.properties
 * item list. Exported for unit testing.
 *
 * @param {{type: string, key?: string, value?: string}[]} properties
 * @param {string} value
 * @returns {{type: string, key?: string, value?: string}[]}
 */
function applyArchitecturesGradleProperty(properties, value) {
  const existing = properties.find(
    (item) => item.type === 'property' && item.key === PROPERTY_KEY,
  );
  if (existing) {
    existing.value = value;
  } else {
    properties.push({ type: 'property', key: PROPERTY_KEY, value });
  }
  return properties;
}

/**
 * @param {import('expo/config-plugins').ExportedConfig} config
 */
const withReleaseArchitectures = (config) => {
  return withGradleProperties(config, (gradleConfig) => {
    gradleConfig.modResults = applyArchitecturesGradleProperty(
      gradleConfig.modResults,
      resolveArchitectures(process.env),
    );
    return gradleConfig;
  });
};

module.exports = withReleaseArchitectures;
module.exports.resolveArchitectures = resolveArchitectures;
module.exports.applyArchitecturesGradleProperty =
  applyArchitecturesGradleProperty;
module.exports.PROPERTY_KEY = PROPERTY_KEY;
module.exports.DEFAULT_ARCHITECTURES = DEFAULT_ARCHITECTURES;
module.exports.ENV_VAR = ENV_VAR;
