/**
 * Config plugin: declare a set of `<uses-feature>` hardware requirements as
 * NOT required in `AndroidManifest.xml`, so Google Play does not use them to
 * filter which devices can see/install the app.
 *
 * Background: after the Ionic→RN migration, Google Play reported the new
 * AAB as incompatible with ~1.672 devices that could install the previous
 * Ionic APK. Part of that gap comes from `<uses-feature>` entries Android's
 * build tooling infers automatically from permissions/APIs used by native
 * dependencies, which default to `android:required="true"` unless a
 * manifest entry says otherwise:
 *
 *   - `android.hardware.wifi` — implied by the `ACCESS_WIFI_STATE`
 *     permission, which `@react-native-community/netinfo` adds to the merged
 *     manifest. The Ionic app never requested that permission, so it never
 *     carried this implied feature, and it worked fine on wifi-less devices
 *     (e.g. phones that are cellular-only) — the app doesn't have a hard
 *     dependency on wifi hardware, it just uses `ACCESS_WIFI_STATE` to read
 *     connectivity state via NetInfo.
 *   - `android.hardware.touchscreen` — Google Play treats this as required
 *     by default for any app unless declared otherwise. The Ionic app never
 *     declared it explicitly (WebView-based apps generally don't), so
 *     declaring it here as optional doesn't remove a real dependency, it
 *     just matches what the previous APK effectively allowed.
 *
 * Marking both as `android:required="false"` tells Play these are
 * capabilities the app can do without, restoring compatibility with the
 * device set the Ionic APK used to reach, without touching any actual
 * runtime behavior (a device without wifi hardware simply never reports a
 * wifi connection to NetInfo; a device without a touchscreen was never
 * something this app supported in practice, but Play's default assumption
 * about it is what excludes those devices from the store listing, not any
 * code in this app).
 *
 * Why a plugin instead of hand-editing `android/app/src/main/AndroidManifest.xml`:
 * `mobile/android/` is generated by `expo prebuild` and is gitignored (see
 * `mobile/.gitignore` → `/android`), so a manual edit is wiped on every
 * prebuild and CI always runs `expo prebuild --clean`. Same reasoning as
 * `withAsyncStorageDbSize.js`, `withReleaseSigning.js` and
 * `withReleaseArchitectures.js`.
 */

const { withAndroidManifest } = require('expo/config-plugins');

/** Hardware features to mark as NOT required (see docblock above). */
const OPTIONAL_FEATURES = [
  'android.hardware.wifi',
  'android.hardware.touchscreen',
];

/**
 * Ensure each feature name in `names` has a `<uses-feature>` entry under
 * `<manifest>` with `android:required="false"`. If an entry for that name
 * already exists (regardless of its current `android:required` value), its
 * `android:required` attribute is updated to `"false"` in place instead of
 * inserting a duplicate `<uses-feature>` element.
 *
 * Exported for unit testing.
 *
 * @param {import('expo/config-plugins').AndroidManifest} manifestJson
 * @param {string[]} names
 * @returns {import('expo/config-plugins').AndroidManifest}
 */
function applyOptionalFeatures(manifestJson, names) {
  const manifest = manifestJson.manifest;
  const usesFeature = manifest['uses-feature'] ?? [];

  for (const name of names) {
    const existing = usesFeature.find(
      (item) => item.$?.['android:name'] === name,
    );
    if (existing) {
      existing.$['android:required'] = 'false';
    } else {
      usesFeature.push({
        $: {
          'android:name': name,
          'android:required': 'false',
        },
      });
    }
  }

  manifest['uses-feature'] = usesFeature;
  return manifestJson;
}

/**
 * @param {import('expo/config-plugins').ExportedConfig} config
 */
const withAndroidOptionalFeatures = (config) => {
  return withAndroidManifest(config, (config) => {
    config.modResults = applyOptionalFeatures(
      config.modResults,
      OPTIONAL_FEATURES,
    );
    return config;
  });
};

module.exports = withAndroidOptionalFeatures;
module.exports.applyOptionalFeatures = applyOptionalFeatures;
module.exports.OPTIONAL_FEATURES = OPTIONAL_FEATURES;
